steps:
  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: Install signing plugin
    inputs:
      signType: $(SignType)

  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.0.100
    inputs:
      packageType: sdk
      version: 3.0.100

  - task: DownloadPipelineArtifact@2
    displayName: Download unsigned payload
    inputs:
      artifact: _osx_payload_unsigned
      path: $(Build.ArtifactStagingDirectory)\layout

  - script: Scalar.Signing\PreSignFiles.Mac.cmd "$(Build.ArtifactStagingDirectory)\layout" "$(Build.ArtifactStagingDirectory)\signroot"
    displayName: Collect files to sign

  # Must use the NuGet & MSBuild toolchain here rather than `dotnet`
  # because the signing tasks target the netfx MSBuild runtime only.
  - task: NuGetCommand@2
    displayName: Restore MicroBuild packages
    inputs:
      command: restore
      restoreSolution: 'Scalar.Signing\Scalar.SignFiles.Mac.csproj'

  - task: MSBuild@1
    displayName: Sign payload
    inputs:
      solution: 'Scalar.Signing\Scalar.SignFiles.Mac.csproj'
      msbuildArguments: '/p:RootDir="$(Build.ArtifactStagingDirectory)\signroot"'

  - script: Scalar.Signing\PostSignFiles.Mac.cmd "$(Build.ArtifactStagingDirectory)\signroot" "$(Build.ArtifactStagingDirectory)\layout"
    displayName: Update layout with signed files

  - task: PublishPipelineArtifact@1
    displayName: Publish signed payload
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)\layout
      artifactName: _osx_payload_signed
